### PR TITLE
Bump 'Tested up to' version to 6.0

### PR DESCRIPTION
**Pull request by kienstra**
* Bump 'Tested up to' version to 6.0
* To deploy to SVN, approve the CircleCI job

### CODE REVIEW

**Comment by kienstra** [comment]
This deployed [as expected](https://plugins.trac.wordpress.org/changeset?old=2282423+&old_path=genesis-author-pro&new=2725591&new_path=genesis-author-pro)

**Review by johnstonphilip — APPROVED** [review]

**Comment by kienstra** [comment]
Thanks a lot, @johnstonphilip!

**Comment by kienstra** [comment]
Hi @dreamwhisper,
Could you review this when you have a chance? Thanks!

**Comment by kienstra** [comment]
Just a sanity check would be great, this already deployed as expected.

**Review by dreamwhisper — APPROVED** [review]

**Comment by kienstra** [comment]
Thanks a lot, @dreamwhisper!

**Pull request merged**
